config/routes.rb
Rails.application.routes.draw do



  

  # resources :campaigns
  resources :users_reports
  get 'home/index'

  mount Attachinary::Engine => "/attachinary"

  scope module: 'admin', path: 'admin' do
  	resources :dashboard, :administradores,
  			  :categories, :interests,
  			  :emissoras, :afiliadas, :levels,
          :usuarios, :advertisers_categories, 
          :advertisers, :notifications,
          :campaigns


    resources :reports do
      collection do
        get 'tv'
        get 'radio'
      end
    end



    match 'usuarios/:id/block_user' => 'usuarios#block_user', via: [:put], as: :block_user
    match 'reports/radio' => 'reports#radio', via: [:get, :post]

    

  end




  namespace 'api' do
    namespace 'v1' do
      resources :dashboard, :administradores,
                :categories, :interests,
                :emissoras, :afiliadas, :levels,
                :usuarios, :advertisers_categories, 
                :advertisers, :notifications,
                :campaigns
    end
  end







  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth' }
  # devise_for :users, :controllers => { :registrations => :registrations }

  devise_scope :user do
    get "/", to: "devise/sessions#new"
    get "sair" => "devise/sessions#destroy"
    get "cadastro" => "devise/registrations#new"
    get 'esqueci-a-senha' => "devise/passwords#new"
    get 'meus-dados/editar' => 'devise/registrations#edit'
    # root :to => "devise/sessions#new"
  end

  devise_for :admin_users, :controllers => { :registrations => :admin_registrations }
  devise_scope :admin_user do
    get "admin", to: "devise/sessions#new"
    get "admin/sair" => "devise/sessions#destroy"
    # get "admin/cadastrar" => "devise/registrations#new"
    # get "admin/cadastrar" => "admin_invitations#new"
    get "admin/cadastrar" => "devise/invitations#new"
    get 'admin/esqueci-a-senha' => "devise/passwords#new"
    get 'admin/meus-dados/editar' => 'devise/registrations#edit', :as => 'editar_usuario'
    # root :to => "devise/sessions#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/users_report.rb
# == Schema Information
#
# Table name: users_reports
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  local      :string
#  lat        :decimal(10, 6)
#  long       :decimal(10, 6)
#  canal      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UsersReport < ApplicationRecord
  belongs_to :user
end

app/controllers/users_reports_controller.rb
class UsersReportsController < SuperAdminController
  before_action :set_users_report, only: [:show, :edit, :update, :destroy]

  # GET /users_reports
  # GET /users_reports.json
  def index
    @users_reports = UsersReport.all
  end

  # GET /users_reports/1
  # GET /users_reports/1.json
  def show
  end

  # GET /users_reports/new
  def new
    @users_report = UsersReport.new
  end

  # GET /users_reports/1/edit
  def edit
  end

  # POST /users_reports
  # POST /users_reports.json
  def create
    @users_report = UsersReport.new(users_report_params)

    respond_to do |format|
      if @users_report.save
        format.html { redirect_to @users_report, notice: 'Users report was successfully created.' }
        format.json { render :show, status: :created, location: @users_report }
      else
        format.html { render :new }
        format.json { render json: @users_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_reports/1
  # PATCH/PUT /users_reports/1.json
  def update
    respond_to do |format|
      if @users_report.update(users_report_params)
        format.html { redirect_to @users_report, notice: 'Users report was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_report }
      else
        format.html { render :edit }
        format.json { render json: @users_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_reports/1
  # DELETE /users_reports/1.json
  def destroy
    @users_report.destroy
    respond_to do |format|
      format.html { redirect_to users_reports_url, notice: 'Users report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_report
      @users_report = UsersReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_report_params
      params.require(:users_report).permit(:user_id, :local, :lat, :long, :canal)
    end
end

app/helpers/users_reports_helper.rb
module UsersReportsHelper
end

app/views/users_reports/_form.html.erb
<%= form_with(model: users_report, local: true) do |form| %>
  <% if users_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_report.errors.count, "error") %> prohibited this users_report from being saved:</h2>

      <ul>
      <% users_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :users_report_user_id %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local, id: :users_report_local %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :users_report_lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long, id: :users_report_long %>
  </div>

  <div class="field">
    <%= form.label :canal %>
    <%= form.text_field :canal, id: :users_report_canal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users_reports/edit.html.erb
<h1>Editing Users Report</h1>

<%= render 'form', users_report: @users_report %>

<%= link_to 'Show', @users_report %> |
<%= link_to 'Back', users_reports_path %>

app/views/users_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Reports</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Local</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Canal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_reports.each do |users_report| %>
      <tr>
        <td><%= users_report.user %></td>
        <td><%= users_report.local %></td>
        <td><%= users_report.lat %></td>
        <td><%= users_report.long %></td>
        <td><%= users_report.canal %></td>
        <td><%= link_to 'Show', users_report %></td>
        <td><%= link_to 'Edit', edit_users_report_path(users_report) %></td>
        <td><%= link_to 'Destroy', users_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users Report', new_users_report_path %>

app/views/users_reports/new.html.erb
<h1>New Users Report</h1>

<%= render 'form', users_report: @users_report %>

<%= link_to 'Back', users_reports_path %>

app/views/users_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_report.user %>
</p>

<p>
  <strong>Local:</strong>
  <%= @users_report.local %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @users_report.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @users_report.long %>
</p>

<p>
  <strong>Canal:</strong>
  <%= @users_report.canal %>
</p>

<%= link_to 'Edit', edit_users_report_path(@users_report) %> |
<%= link_to 'Back', users_reports_path %>